# Generated by Django 5.0.4 on 2024-04-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_forumtopic_remove_forumpost_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ['-updated', '-date_created']},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='messaageforum',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
